version: "3"
services:
  clojure-dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - dev.env
    volumes:
      - ./code:/code
      - ./deps:/deps
    tty: true
    stdin_open: true
